### ISSUE TITLE
Error en el ultimo mensaje al finalizar

### ISSUE THREAD

**Issue by GianfrancoParionaMendoza** [reyalexander/Trivia-1--Alexander-Cayro#2]
#Bug

Este error en el código genera que la variable **"nombre"** que está anidado al **"print"** no funcione y lo tome como texto. lo que recomendaría sería:

- [nombre="juan"
print("\nEspero ",nombre," que lo hayas pasado bien, hasta pronto!") ] 

![Captura de pantalla 2022-09-17 103653](https://user-images.githubusercontent.com/105090146/190865304-52a34b51-adce-4896-9e1e-eb887ba26582.png)
![Captura de pantalla 2022-09-17 104033](https://user-images.githubusercontent.com/105090146/190865307-699904f0-e819-4004-a238-66e2ed2cc448.png)

**Comment by reyalexander** [comment]
Gracias por la acotación, no me había dado cuenta de ese pequeño error.
